# -------------------------------------------------------------------------------------------------------------------------------------|
#                           Development Connection Details                                                                              |
# -------------------------------------------------------------------------------------------------------------------------------------|

Production:
  datasource:
    HostAddress: 20.51.185.108
    Username: yugabyte
    Password: SGFja2F0aG9uMjIh
    PortNo: 5433
    Database: yugabyte